### ISSUE TITLE
Currency exponent for USD Ledger Accounts defaults to 0 from 2

### ISSUE THREAD

**Issue by janduguran** [Modern-Treasury/modern-treasury-node#258]
Hello,

We recently noticed that the currency exponent for newly created ledger accounts with USD currency defaults to `0`. Previously this was set to `2`. 
Based on the [documentation ](https://docs.moderntreasury.com/platform/docs/currencies) for USD currencies the smallest unit is in cents (currency exponent is 2).

Is this a bug or is this the new behavior?

Thank you.

**Environment**: Sandbox

**Comment by samridh90** [comment]
@janduguran : This should be fixed now. Can you try again?

**Comment by janduguran** [comment]
@samridh90 All good. Thanks.
