### ISSUE TITLE
ModernTreasury.Invoices.InvoiceCreateParams Typescript Interface not matching API documentation

### ISSUE THREAD

**Issue by nirmpate** [Modern-Treasury/modern-treasury-node#467]
There are fields not present in the typescript interface ModernTreasury.Invoices.InvoiceCreateParams that appear in the API docs for Invoice Create. 

https://docs.moderntreasury.com/platform/reference/create-invoice

```
auto_advance
metadata
```

I believe these 2 fields should be available to pass to invoices.create()

**Comment by dgellow** [comment]
Hi @nirmpate. Thanks for the report, that does indeed look like discrepancies between the API and the SDK.

We are looking into it.

**Comment by dgellow** [comment]
That has been fixed with https://github.com/Modern-Treasury/modern-treasury-node/pull/465.

Could you try to upgrade to v2.31.0 and confirm the issue is fixed?
