### ISSUE TITLE
Can't configure the default max retries for all requests

### ISSUE THREAD

**Issue by jetoneza** [Modern-Treasury/modern-treasury-node#91]
The example in the documentation shows that you can configure the default max retries for all `requests` when instantiating the API client. 

The config `maxRetries` does not exist in the type `Config` of the API client's constructor and therefore can't configure the default max retries for all request.

Thank you in advance for the help!

**Comment by RobertCraigie** [comment]
Hey @jetoneza, sorry about this & thank you for the bug report! We will have a fix out shortly.

**Comment by jetoneza** [comment]
Thank you very much @RobertCraigie!

**Comment by rattrayalex** [comment]
This was added here: https://github.com/Modern-Treasury/modern-treasury-node/pull/98/files#diff-dcdc3e0b3362edb8fec2a51d3fa51f8fb8af8f70247e06d9887fa934834c9122R18
